In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F 
import torch.backends.cudnn as cudnn

import torchvision
import torchvision.transforms as transforms

import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib.pylab as plt2
import os

from models import *


# from resnet50 import ResNet50
# from resnet34 import ResNet34

from torch.optim.lr_scheduler import ReduceLROnPlateau


C:\Users\mrtz\anaconda3\envs\mtp\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [20]:
#Check GPU, connect to it if it is available 
device = ''
if torch.cuda.is_available():
	device = 'cuda'
	print("CUDA is available. GPU will be used for training.")
else:
	device = 'cpu'

In [23]:
BEST_ACCURACY = 0

# Preparing Data
print("==> Prepairing data ...")
#Transformation on train data
transform_train = transforms.Compose([
	transforms.RandomCrop(32, padding=4),
	transforms.RandomHorizontalFlip(),
	transforms.ToTensor(),
	transforms.Normalize((0.4914, 0.4822, 0.4465),(0.2023, 0.1994, 0.2010)),
	])

#transformation on validation data
transform_validation = transforms.Compose([
	transforms.ToTensor(),
	transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
	])

#Download Train and Validation data and apply transformation
train_data = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_train)
validation_data = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_validation)

#Put data into trainloader, specify batch_size
train_loader = torch.utils.data.DataLoader(train_data, batch_size=128, shuffle=True, num_workers=2)
validation_loader = torch.utils.data.DataLoader(validation_data, batch_size=128, shuffle=True, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

#Function to show CIFAR images
def show_data(image):
	plt.imshow(np.transpose(image[0], (1, 2, 0)), interpolation='bicubic')
	plt.show()

#show_data(train_data[0])




==> Prepairing data ...
Files already downloaded and verified
Files already downloaded and verified


In [43]:
#Need to import model a model
# model = ResNet50()
# model = ResNet34Cifar10(num_classes = 10)
model = ResNet([3,4,6,3])
# model = ResNet34_x()
# print(model)
#model = CNN_batch()
#Pass model to GPU
# model = model.to(device)
# model.train()
optimizer = optim.SGD(model.parameters(), lr = 0.01, momentum=0.9, weight_decay=5e-4)
criterion = nn.CrossEntropyLoss()
scheduler = ReduceLROnPlateau(optimizer, mode='max', factor=0.1, patience=5, verbose=True)



length_train = len(train_data)
length_validation = len(validation_data)
#print(length_train)
#print(len(train_loader))
num_classes = 10

AttributeError: 'NoneType' object has no attribute 'parameters'

In [28]:
checkpoint = torch.load('./Results/resnet34/resnet34_own_8996.pth')
print(checkpoint)

OrderedDict([('conv1.weight', tensor([[[[-0.1198,  0.0945,  0.0392],
          [-0.0255,  0.0169, -0.0819],
          [ 0.0123,  0.1839, -0.1759]],

         [[-0.0539,  0.2145, -0.1533],
          [ 0.1741,  0.0221, -0.1485],
          [ 0.0135,  0.1526, -0.0679]],

         [[ 0.0750, -0.0468,  0.0780],
          [-0.0049,  0.1560, -0.1560],
          [-0.0412, -0.1330, -0.0467]]],


        [[[-0.0205, -0.0074, -0.0727],
          [-0.0805,  0.0486, -0.0530],
          [-0.1077,  0.0345, -0.1196]],

         [[ 0.1258, -0.1372, -0.0710],
          [ 0.0868, -0.0922,  0.1084],
          [-0.0460,  0.0705, -0.0508]],

         [[-0.1370,  0.0371, -0.1317],
          [-0.1532,  0.0572, -0.0715],
          [-0.0830, -0.1185, -0.0586]]],


        [[[ 0.1587,  0.1353,  0.1342],
          [-0.1307,  0.1242,  0.0979],
          [-0.0832,  0.0412, -0.0890]],

         [[ 0.0733, -0.0509, -0.0283],
          [ 0.0421,  0.1116, -0.1752],
          [ 0.0188, -0.0904, -0.1959]],

         [[ 0.

In [41]:
# Load the checkpoint
checkpoint = torch.load('./Results/resnet34/train_save/resnet34_own_8996.pth')

# print(checkpoint)

# Create a new model without the linear layer
# model.backbone = ResNet34_class()

# Load the state_dict of the backbone model from the checkpoint
model.backbone.load_state_dict(checkpoint, strict=False)

# Print the weights of each layer
for name, param in backbone.named_parameters():
    if param.requires_grad:
        print(f'Layer: {name}, Shape: {param.data.shape}')
        print(param.data)

# Save the backbone model
torch.save(backbone.state_dict(), './Results/resnet34/backbone34_own.pth')

Layer: conv1.weight, Shape: torch.Size([64, 3, 3, 3])
tensor([[[[-0.1198,  0.0945,  0.0392],
          [-0.0255,  0.0169, -0.0819],
          [ 0.0123,  0.1839, -0.1759]],

         [[-0.0539,  0.2145, -0.1533],
          [ 0.1741,  0.0221, -0.1485],
          [ 0.0135,  0.1526, -0.0679]],

         [[ 0.0750, -0.0468,  0.0780],
          [-0.0049,  0.1560, -0.1560],
          [-0.0412, -0.1330, -0.0467]]],


        [[[-0.0205, -0.0074, -0.0727],
          [-0.0805,  0.0486, -0.0530],
          [-0.1077,  0.0345, -0.1196]],

         [[ 0.1258, -0.1372, -0.0710],
          [ 0.0868, -0.0922,  0.1084],
          [-0.0460,  0.0705, -0.0508]],

         [[-0.1370,  0.0371, -0.1317],
          [-0.1532,  0.0572, -0.0715],
          [-0.0830, -0.1185, -0.0586]]],


        [[[ 0.1587,  0.1353,  0.1342],
          [-0.1307,  0.1242,  0.0979],
          [-0.0832,  0.0412, -0.0890]],

         [[ 0.0733, -0.0509, -0.0283],
          [ 0.0421,  0.1116, -0.1752],
          [ 0.0188, -0.0904, -0

tensor([[[[-7.7925e-05,  2.3696e-03,  9.6732e-03],
          [ 1.2101e-02, -6.2154e-03,  4.6912e-03],
          [ 1.6740e-03, -9.1169e-03, -1.0983e-02]],

         [[ 4.5565e-05,  5.0729e-03,  8.0097e-03],
          [-5.0214e-03, -1.1125e-02, -3.1763e-03],
          [ 1.2461e-03, -8.9459e-03,  5.7382e-03]],

         [[ 5.3823e-03,  7.7523e-03,  4.6058e-03],
          [ 2.1359e-03, -3.6922e-03,  7.0236e-03],
          [ 4.7164e-03,  3.7111e-03,  6.0048e-03]],

         ...,

         [[-8.3211e-03, -2.1817e-03, -5.6471e-03],
          [-8.7314e-03,  1.2362e-03,  5.0380e-03],
          [-2.8860e-03, -2.9265e-03,  8.1902e-03]],

         [[-4.5809e-03,  5.8944e-03,  5.9472e-03],
          [ 9.5545e-03,  9.6089e-03,  6.3149e-04],
          [ 1.3924e-04,  4.0081e-03, -1.1819e-02]],

         [[-8.7281e-03, -1.0133e-02, -6.8024e-03],
          [ 2.0965e-03, -7.8784e-03,  9.6582e-03],
          [-9.1467e-03, -6.1114e-03,  7.4811e-03]]],


        [[[-1.0547e-02,  6.4048e-03, -1.1877e-02],
  

In [42]:
# Load the checkpoint
checkpoint = torch.load('./Results/resnet34/backbone34_own.pth')

# Create a new model without the linear layer
model.backbone.load_state_dict(checkpoint)

# Print the weights of each layer
for name, param in backbone.named_parameters():
    if param.requires_grad:
        print(f'Layer: {name}, Shape: {param.data.shape}')
        print(param.data)

Layer: conv1.weight, Shape: torch.Size([64, 3, 3, 3])
tensor([[[[-0.1198,  0.0945,  0.0392],
          [-0.0255,  0.0169, -0.0819],
          [ 0.0123,  0.1839, -0.1759]],

         [[-0.0539,  0.2145, -0.1533],
          [ 0.1741,  0.0221, -0.1485],
          [ 0.0135,  0.1526, -0.0679]],

         [[ 0.0750, -0.0468,  0.0780],
          [-0.0049,  0.1560, -0.1560],
          [-0.0412, -0.1330, -0.0467]]],


        [[[-0.0205, -0.0074, -0.0727],
          [-0.0805,  0.0486, -0.0530],
          [-0.1077,  0.0345, -0.1196]],

         [[ 0.1258, -0.1372, -0.0710],
          [ 0.0868, -0.0922,  0.1084],
          [-0.0460,  0.0705, -0.0508]],

         [[-0.1370,  0.0371, -0.1317],
          [-0.1532,  0.0572, -0.0715],
          [-0.0830, -0.1185, -0.0586]]],


        [[[ 0.1587,  0.1353,  0.1342],
          [-0.1307,  0.1242,  0.0979],
          [-0.0832,  0.0412, -0.0890]],

         [[ 0.0733, -0.0509, -0.0283],
          [ 0.0421,  0.1116, -0.1752],
          [ 0.0188, -0.0904, -0

tensor([[[[-1.1225e-02, -6.2670e-03, -2.3473e-04],
          [-5.5303e-03, -9.5616e-03,  2.1941e-04],
          [ 1.3786e-03,  2.9356e-03,  1.4072e-03]],

         [[ 1.0050e-02, -2.7155e-03, -1.0383e-02],
          [-1.3182e-02,  5.3918e-03,  3.6614e-03],
          [-8.7436e-03,  1.1120e-02,  7.0469e-03]],

         [[ 7.8125e-03,  1.5164e-03, -1.2180e-03],
          [ 9.3708e-03,  5.2353e-03, -4.5590e-03],
          [ 4.4143e-03,  8.7247e-03, -6.7238e-04]],

         ...,

         [[ 2.2355e-03,  1.2072e-02,  2.5306e-03],
          [ 6.4290e-03, -1.7885e-03, -7.7184e-03],
          [-1.2078e-03, -3.3889e-03,  4.9355e-03]],

         [[-1.1486e-02, -1.0331e-02,  7.0115e-03],
          [ 6.6835e-03, -9.2961e-03,  4.5594e-03],
          [ 6.6909e-03,  9.2909e-03,  7.6372e-03]],

         [[-8.9081e-03,  9.0240e-03, -5.2192e-03],
          [ 5.9930e-03, -1.4398e-03, -7.9885e-03],
          [ 6.3344e-04, -7.0134e-03,  3.2768e-03]]],


        [[[ 6.2470e-03,  1.3650e-03,  5.1594e-03],
  

In [8]:
checkpoint = torch.load('./Results/resnet34/resnet34_own_8996.pth')
# model.load_state_dict(checkpoint)

# Load the state_dict of the backbone model, excluding the linear layer parameters
state_dict = {k: v for k, v in checkpoint.state_dict().items() if 'linear' not in k}
model.load_state_dict(state_dict, strict=False)

# Save the backbone model
torch.save(backbone.state_dict(), './Results/resnet34/backbone34_own.pth')

AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'

In [ ]:
checkpoint = torch.load('./Results/resnet34/backbone_34_new.pth')
model.backbone.load_state_dict(checkpoint)

checkpoint = torch.load('./Results/resnet34/linear_34_new.pth')
model.linear.load_state_dict(checkpoint)

In [ ]:
# # Save the layers except the linear layer
# layer_dict = {}
# for name, layer in model.named_children():
#     if name != 'linear':
#         layer_dict[name] = layer.state_dict()

# # Save the linear layer separately
# linear_dict = model.linear.state_dict()

# torch.save(layer_dict, './Results/resnet34/backbone_34_new.pth')
# torch.save(linear_dict, './Results/resnet34/linear_34_new.pth')